version: '3'

services:
  # PostgreSQL Database Container
  db:
    image: postgres:latest  # Use the latest official PostgreSQL image
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"  # Map local port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
